artifacts_root: artifacts

data_ingestion : 
  root: artifacts/data_ingestion
  source_dir : data/raw/spam.csv
  train_dir : artifacts/data_ingestion/train.csv
  test_dir : artifacts/data_ingestion/test.csv

data_validation:
  root: artifacts/data_validation
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  required_columns:
    - text
    - label
  target_column: label


data_preprocessing:
  root: artifacts/data_preprocessing
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  processed_train_path: artifacts/data_preprocessing/train_processed.csv
  processed_test_path: artifacts/data_preprocessing/test_processed.csv
  vectorizer_path: artifacts/data_preprocessing/tfidf_vectorizer.pkl
  text_column: text
  target_column: label


model_trainer:
  root: artifacts/model_trainer
  train_data_path: artifacts/data_preprocessing/train_processed.csv
  test_data_path: artifacts/data_preprocessing/test_processed.csv
  model_dir: artifacts/model_trainer/models
  target_column: label
  experiment_name: spam_detection_experiment

model_evaluation:
  root: artifacts/model_evaluation
  model_path: artifacts\model_trainer\models\LinearSVM.pkl
  test_data_path: artifacts/data_preprocessing/test_processed.csv
  target_column: label
  metrics_path: artifacts/model_evaluation/metrics.json
