artifacts_root: artifacts

data_ingestion : 
  root: artifacts/data_ingestion
  source_dir : data/raw/spam.csv
  train_dir : artifacts/data_ingestion/train.csv
  test_dir : artifacts/data_ingestion/test.csv

data_validation:
  root: artifacts/data_validation
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  required_columns:
    - text
    - label
  target_column: label
